finance_data_platform:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCP_KEYFILE') }}"
      project: finance-data-platform-503113
      dataset: dbt_dev
      location: EU
      priority: interactive
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
    ci:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCP_KEYFILE') }}"
      project: finance-data-platform-503113
      dataset: dbt_ci
      location: EU
      priority: interactive
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1